FirstName=input('Input Your First Name: ')
LastName=input('Input Your Last Name: ')
Address=input('Input Your Address: ')
City=input('Input Your City: ')
StateCode=input('Input Your State Code: ')
ZipCode=input('Input Your Zipcode/Postal Code: ')
print(FirstName, LastName,'\n',Address,'\n',City,",",StateCode,",",ZipCode)
