from graphics import *
win = GraphWin ('AAAAAAAAAAA',500,500)
win.setBackground ('white')
maincirc = Circle(Point(250,250),200)
maincirc.setWidth (3)
maincirc.setOutline ('light green')
maincirc.draw(win)
Leye = Circle(Point(180,180),50)
Leye.setOutline ('red')
Leye.setFill ('red')
Leye.draw(win)
Reye = Circle(Point(325,180),50)
Reye.setOutline ('blue')
Reye.setFill ('blue')
Reye.draw(win)
line = Rectangle(Point(180,300),Point(330,275))
line.setOutline ('yellow')
line.setFill('yellow')
line.draw(win)
Poly = Polygon(Point (180,398), Point(330,400),
               Point(260,480))
Poly.setOutline ('black')
Poly.setWidth (22)
Poly.draw(win)
