#Program number 20
from turtle import *
import time
speed (12)
pencolor ('light green')
pensize (6)
penup()
setposition (0,-200)
pendown()
circle (250)
penup()
setposition (-100,100)
pendown()
pencolor ('red')
fillcolor ('red')
begin_fill()
circle (65)
end_fill()
penup()
setposition (100,100)
pendown()
pencolor ('blue')
fillcolor ('blue')
begin_fill()
circle (65)
end_fill()
penup()
setposition (-100,20)
pencolor('yellow')
pensize (30)
pendown()
forward(200)
penup()
setposition (-100,-120)
pencolor ('black')
pendown()
forward (200)
right (130)
forward (150)
right (98)
forward (150)



